begin;

create table if not exists public.api_request_metrics (
  id bigint generated by default as identity primary key,
  route text not null,
  method text not null,
  status integer not null,
  duration_ms integer not null default 0,
  request_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_api_request_metrics_created_at
  on public.api_request_metrics (created_at desc);

create index if not exists idx_api_request_metrics_route_method
  on public.api_request_metrics (route, method);

alter table public.api_request_metrics enable row level security;

do $$ begin
  create policy "Admins can read api metrics"
    on public.api_request_metrics
    for select
    to authenticated
    using (
      exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role = 'admin'
          and p.is_active = true
      )
    );
exception when duplicate_object then null; end $$;

commit;
